# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Building Docker image to ACR
  inputs:
    containerRegistry: 'nomzeeacr'
    repository: 'trending-lagos-restuarants'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: HelmInstaller@0
  displayName: Installing Helm tool
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true

- task: HelmDeploy@0
  displayName: Creating Helm Package
  inputs:
    command: 'package'
    chartPath: 'helm'
    chartVersion: '$(Build.Buildid)'

- task: PublishBuildArtifacts@1
  displayName: Publishing packaged artifact.
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'restaurants'
    publishLocation: 'Container'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)'
#     artifact: 'restuarants'
#     publishLocation: 'pipeline'


